db_host: 'example.com'
db_port: 1234
db_name: 'mydatabase'
db_user: 'myusername'

db_type: 'sqlite'
db_path: 'sqlite:///databases/table_diff_test.db'
schema_name: 'public'

table_initial: 'testing_0'
table_secondary: 'testing_1'
diff_table: '__diff-table__' # default to __diff_table))
key_columns: ['id']
compare_cols: []
ignore_cols: []

initial_table_alias: 'origin'
secondary_table_alias: 'comparison'
