db_host: 'example.com'
db_port: 1234
db_name: 'mydatabase'
db_user: 'myusername'

db_type: 'sqlite'
db_path: 'sqlite:///databases/table_diff_test.db'
  # used for machine 1
  #db_path: 'sqlite:///home/benjamin-farmer/Envs/sanjuandata/local_db/sqlite/Diff_test.db'
  # used for machine 0
table_initial: 'testing_0'
table_secondary: 'testing_1'
diff_table: '__d__' # default to __diff_table))
key_columns: ['id']
schema: 'public'

initial_table_name: 'origin'
secondary_table_name: 'comparison'
